[build]
  base = "src"
  command = "npm run build"
  publish = "dist"
  environment:
  NODE_ENV = "production"

[functions]
  directory = "src/backend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200